<img src = 'https://github.com/insaid2018/Term-1/blob/master/Images/INSAID_Full%20Logo.png?raw=true' width="240" height="360">
# __Assignment: Numpy and Pandas__
### Level: 1

### 1. Create a null vector of size 7 but the third and last value as 2.

In [4]:
import numpy as np
def generate():
    # Write your code here
    x = np.zeros(7)
    # print(x)
    x[2] = 2
    x[6] = 2
    # print(x)
    return x                    # your variable 
generate()

array([0., 0., 2., 0., 0., 0., 2.])

### 2. Create a vector of size 9 with values ranging from 0 to 2, both excluded.

In [2]:
import numpy as np
def generate():
    # Write your code here
    Vector = np.linspace(0, 2, num=11, endpoint=True)[1:-1]
    return Vector # your variable
generate()

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

### 3. Convert the first character of each element in a series to uppercase? And return the new series.

In [4]:
import pandas as pd
series = pd.Series(['how', 'to', 'learn', 'data science?'])
def generate():
    # your code
    new_series = series.map(lambda x: x[0].upper() + x[1:])
    return new_series # your variable for new series
generate() 

0              How
1               To
2            Learn
3    Data science?
dtype: object

### 4. Given a 3*3 matrix named matrix_fab, From each element of this matrix subtract the mean of that row, name this matrix as matrix_sub. Divide each element of this matrix by twice of the largest element to get matrix_norm. Print it out.

In [6]:
import numpy as np
arr = np.arange(0,9)                                
matrix_fab = arr.reshape(3,3)
def generate():
    # Write your code here
    matrix_sub = matrix_fab - matrix_fab.mean(axis=1, keepdims=True)
    # print(matrix_sub)
    max = matrix_sub.max()
    matrix_norm = matrix_sub/(2*max)
    print(matrix_norm)
    # print matrix_norm
    return None
generate()

[[-0.5  0.   0.5]
 [-0.5  0.   0.5]
 [-0.5  0.   0.5]]


### 5. Create a random vector of size 12 , sort it in decreasing order, make 4*3 array using it.
Hint: use reshape and sort function.

In [8]:
import numpy as np
def generate():
    # Write your code here
    rand_vector = np.random.random(12)
    rand_sort = np.array(sorted(rand_vector, reverse=True))
    rand_new = rand_sort.reshape(4,3)
    return rand_new # your variable
generate()

array([[0.9402375 , 0.85034365, 0.74483399],
       [0.68556591, 0.57830532, 0.41139956],
       [0.35231072, 0.34861574, 0.21683197],
       [0.13224644, 0.05492483, 0.01734988]])

### 6. Below is Python dictionary data and Python list labels. Create a DataFrame df from this dictionary data which has index as labels. Select the rows where the age is missing, i.e. is NaN.

In [11]:
import numpy as np
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
import pandas as pd
def generate():
    # Write your code here
    df = pd.DataFrame(data, index=labels)
    print(df[df['age'].isnull()])
    return # your variable
generate()

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes


### 7. From the give dataframe df, in the 'animal' column change the 'dog' entries to 'Labrador', change the age in row 'd' to 2.7 and calculate the mean age (name it mean_age) for each different animal in df. Print df and return mean_age.

In [16]:
import pandas as pd
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(data, index=labels)
def generate():
    # write your code here
    df['animal'] = df['animal'].replace('dog' , 'Labrador')
    df.loc['d','age'] = 2.7
    mean_age = df.groupby('animal')['age'].mean()
    # Also print df
    print(df)
    return mean_age # your variable i.e mean_age
generate()

     animal  age  visits priority
a       cat  2.5       1      yes
b       cat  3.0       3      yes
c     snake  0.5       2       no
d  Labrador  2.7       3      yes
e  Labrador  5.0       2       no
f       cat  2.0       3       no
g     snake  4.5       1       no
h       cat  NaN       1      yes
i  Labrador  7.0       2       no
j  Labrador  3.0       1       no


animal
Labrador    4.425
cat         2.500
snake       2.500
Name: age, dtype: float64

### 8.  From the given dataframe get the positions where values of two columns match?

In [21]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})
def generate():
    # your code here
    s = np.where(df.fruit1 == df.fruit2)
    print(s)
    return None
generate()

(array([0, 5, 6, 8], dtype=int64),)


### 9. Find the positions of numbers that are multiples of 4 from a series? Print series and return position. Hint: use argwhere.

In [27]:
import pandas as pd
import numpy as np
series = pd.Series(np.random.randint(1, 10, 7))
def generate():
    # your code here
    pos = np.argwhere(series % 4 == 0)
    print(series)
    print(pos)
    return pos # your variable
generate()

0    1
1    5
2    9
3    4
4    8
5    4
6    8
dtype: int32
[[3]
 [4]
 [5]
 [6]]


array([[3],
       [4],
       [5],
       [6]], dtype=int64)

### 10. Stack two given series vertically and horizontally ? Print out both.

In [33]:
import pandas as pd
import numpy as np
series1 = pd.Series(range(5))
series2 = pd.Series(list('abcde'))
print(series1)
print(series2)
def generate():
    # your code
    verti = series1.append(series2)
    print(verti)
    
    hori = pd.concat([series1, series2], axis = 1)
    print(hori)
    # print out both vertically and horizontally stacked series.
    return None
generate()

0    0
1    1
2    2
3    3
4    4
dtype: int64
0    a
1    b
2    c
3    d
4    e
dtype: object
0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object
   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e
