<img src = 'https://github.com/insaid2018/Term-1/blob/master/Images/INSAID_Full%20Logo.png?raw=true' width="240" height="360">
# __Assignment: Numpy and Pandas__
### Level: 2

### 1. Form a 1D array containing elements from -2(including) to 10(excluding) in arithmetic progression with common difference 1.5 , negate all elements which are between 2 and 7, in place. Print out this new array.

In [12]:
import numpy as np
def generate():
    # your code here
    arr = np.arange(-2, 10, 1.5)
    arr[(arr>2) & (arr<7)] *= -1
    #print(arr)
    return arr # return modified array
generate()

array([-2. , -0.5,  1. , -2.5, -4. , -5.5,  7. ,  8.5])

### 2. Create random vector of size 7 and replace the maximum value by 2 and minimum by 7. Sort this array in reverse order. Return the modified vector.

In [19]:
import numpy as np
def generate():
    # your code
    random_vctr = np.random.random(7)
    print(random_vctr)
    random_vctr[random_vctr.argmax()] = 2
    random_vctr[random_vctr.argmin()] = 7
    print(random_vctr)
    modified_vctr = np.array(sorted(random_vctr, reverse=True))
    return modified_vctr # your array
generate()

[0.02666116 0.30356635 0.01881451 0.55704674 0.10920563 0.67435022
 0.3845939 ]
[0.02666116 0.30356635 7.         0.55704674 0.10920563 2.
 0.3845939 ]


array([7.        , 2.        , 0.55704674, 0.3845939 , 0.30356635,
       0.10920563, 0.02666116])

### 3. Convert a random 7x2 matrix representing cartesian coordinates to polar coordinates. Print out both.
Hint: use arctan2().

In [23]:
import numpy as np
def generate():
    # your code here
    matrix = np.random.random((7,2))
    print(matrix)
    row, column = matrix[:,0], matrix[:,1]
    radial_coordinate = np.sqrt(row**2, column**2)
    angular_coordinate = np.arctan2(column, row)
    print(radial_coordinate)
    print(angular_coordinate)
    # print out both matrices
    return None
generate()

[[0.94615813 0.53050717]
 [0.15798012 0.26695148]
 [0.51544726 0.45702855]
 [0.4028712  0.98142391]
 [0.88064809 0.57077782]
 [0.92231745 0.34236358]
 [0.25697436 0.05299177]]
[0.94615813 0.15798012 0.51544726 0.4028712  0.88064809 0.92231745
 0.25697436]
[0.51101808 1.03643296 0.72539812 1.18127402 0.57506221 0.35543438
 0.20336357]


### 4. Create an numpy array sequence named num_seq when only the starting point, step size and length of sequence is given.

In [24]:
import numpy as np

length = 15
start = 5
step = 2

def generate(start, length, step):
    # your code here
    end = start + (step * length)
    num_seq = np.arange(start, end, step)
    return num_seq # array created by you, i.e. num_seq
generate(start, length, step)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

### 5. Make a 3*3 array using a 1d array of evenly spaced numbers ranging from 0 to 9, name it arr1.<br/> 
### Then transpose it to obtain arr2.  From arr2 subtract a 1*3 array with all elements 1 to get arr4.
HINT: Use reshape and transpose function.

In [35]:
import numpy as np
def generate():
    # your code here
    arr = np.arange(9)
    print(arr)
    arr1 = arr.reshape(3,3)
    print(arr1)
    arr2 = arr1.transpose()
    print(arr2)
    arr3 = np.ones(3, dtype=int)
    print(arr3)
    arr4 = arr2 - arr3
    return arr4 # finally created array i.e arr4
generate()

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
[1 1 1]


array([[-1,  2,  5],
       [ 0,  3,  6],
       [ 1,  4,  7]])

### 6. Create a DatetimeIndex that contains each business day of 2016 and use it to index a Series of random numbers. Let's call this Series bus_2k16. Print it out. Hint: use pd.date_range.

In [39]:
import pandas as pd
import numpy as np
def generate():
    # Your code here
    date_time_index = pd.date_range(start='2016-01-01', end='2016-12-31', freq='B')
    print(date_time_index)
    bus_2K16 = pd.Series(np.random.rand(len(date_time_index)), index=date_time_index)
    print(bus_2K16)
    # print out bus_2k16
    return None
generate()

DatetimeIndex(['2016-01-01', '2016-01-04', '2016-01-05', '2016-01-06',
               '2016-01-07', '2016-01-08', '2016-01-11', '2016-01-12',
               '2016-01-13', '2016-01-14',
               ...
               '2016-12-19', '2016-12-20', '2016-12-21', '2016-12-22',
               '2016-12-23', '2016-12-26', '2016-12-27', '2016-12-28',
               '2016-12-29', '2016-12-30'],
              dtype='datetime64[ns]', length=261, freq='B')
2016-01-01    0.332543
2016-01-04    0.414324
2016-01-05    0.289214
2016-01-06    0.015003
2016-01-07    0.105240
2016-01-08    0.083084
2016-01-11    0.763328
2016-01-12    0.391913
2016-01-13    0.987388
2016-01-14    0.544673
2016-01-15    0.781433
2016-01-18    0.648657
2016-01-19    0.036320
2016-01-20    0.102481
2016-01-21    0.068109
2016-01-22    0.699470
2016-01-25    0.186849
2016-01-26    0.092462
2016-01-27    0.344711
2016-01-28    0.650255
2016-01-29    0.184863
2016-02-01    0.451130
2016-02-02    0.148130
2016-02-03    0.91921

###  7. For each calendar month in dataframe bus_2k16, from previous problem. Print out the mean of values also find the sum of the values in bus_2k16 for every Sunday.

In [42]:
import pandas as pd
def generate():
    # Your code here
    date_time_index = pd.date_range(start='2016-01-01', end='2016-12-31', freq='B')
    print(date_time_index)
    bus_2K16 = pd.Series(np.random.rand(len(date_time_index)), index=date_time_index)
    print(bus_2K16)
    # print out mean
    print(bus_2K16.resample('M').mean())
    print(bus_2K16[bus_2K16.index.weekday == 0].sum())
    # print out sum of the values in bus_2k16 for every Sunday.
    return None
generate()

DatetimeIndex(['2016-01-01', '2016-01-04', '2016-01-05', '2016-01-06',
               '2016-01-07', '2016-01-08', '2016-01-11', '2016-01-12',
               '2016-01-13', '2016-01-14',
               ...
               '2016-12-19', '2016-12-20', '2016-12-21', '2016-12-22',
               '2016-12-23', '2016-12-26', '2016-12-27', '2016-12-28',
               '2016-12-29', '2016-12-30'],
              dtype='datetime64[ns]', length=261, freq='B')
2016-01-01    0.511465
2016-01-04    0.859764
2016-01-05    0.350747
2016-01-06    0.328893
2016-01-07    0.744469
2016-01-08    0.039281
2016-01-11    0.656153
2016-01-12    0.704680
2016-01-13    0.571295
2016-01-14    0.706490
2016-01-15    0.416835
2016-01-18    0.173019
2016-01-19    0.200931
2016-01-20    0.341487
2016-01-21    0.701570
2016-01-22    0.975988
2016-01-25    0.183207
2016-01-26    0.185096
2016-01-27    0.561117
2016-01-28    0.281987
2016-01-29    0.053547
2016-02-01    0.875473
2016-02-02    0.217658
2016-02-03    0.61192

### 8.Given the dataframe df, In the From_To column split each string on the underscore delimiter _ to give a new temporary DataFrame with the correct values. Also standardise the strings so that only the first letter is uppercase (e.g. "londON" should become "London".) Assign the correct column names to this temporary DataFrame named as temp. Return temp.

In [54]:
import numpy as np
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})
import pandas as pd
def generate():
    # write your code here
    temp = df.From_To.str.split('_', expand=True)
    print(temp)
    temp.columns = ['From', 'To']
    temp['From'] = temp['From'].str.capitalize()
    temp['To'] =  temp['To'].str.capitalize()
    return temp# your temporary variable i.e temp.
generate()

          0          1
0    LoNDon      paris
1    MAdrid      miLAN
2    londON  StockhOlm
3  Budapest      PaRis
4  Brussels     londOn


From         To
0    London      Paris
1    Madrid      Milan
2    London  Stockholm
3  Budapest      Paris
4  Brussels     London

### 9. Given a dataFrame with 10 columns of real numbers. Find that column's label which has the smallest sum? Also count the number of unique rows the dataframe has. 
Hint: use idxmin method.

In [71]:
import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.random(size=(4, 10)), columns=list('qrstuvwxyz'))
print(df)
def generate():
    # your code here
    # print out that column's label which has the smallest sum
    print(df.sum().idxmin())
    # Also count the number of unique rows the dataframe has.
    print(len(df) - df.duplicated(keep=False).sum())
    return None
generate()

          q         r         s         t         u         v         w  \
0  0.060081  0.312706  0.090696  0.262264  0.767557  0.455118  0.357038   
1  0.010063  0.133404  0.509903  0.563631  0.394074  0.244053  0.309541   
2  0.878645  0.484854  0.770824  0.810844  0.722956  0.448734  0.619920   
3  0.688907  0.977954  0.855719  0.547504  0.908084  0.563436  0.684163   

          x         y         z  
0  0.892344  0.611219  0.307781  
1  0.724968  0.286276  0.130586  
2  0.949215  0.484717  0.639155  
3  0.714349  0.735727  0.849969  
q
4


### 10. Given a dataFrame df with a column 'int' of integers. Print out the dataframe with filtered out rows which contain the same integer as the row immediately above. Also print out the dataframe after subtracting the mean of all integers from each element .
Hint: use drop_duplicates and sub methods

In [74]:
import pandas as pd
df = pd.DataFrame({'int': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
def generate():
    # your code here
    # Print out the dataframe with filtered out rows which contain the same integer as the row immediately above
    print(df.drop_duplicates(subset='int'))
    # Print out the dataframe after subtracting the mean of all integers from each element
    print(df.sub(df.mean(axis=0), axis=1))
    return None
generate()

   int
0    1
1    2
3    3
4    4
5    5
8    6
9    7
         int
0  -3.272727
1  -2.272727
2  -2.272727
3  -1.272727
4  -0.272727
5   0.727273
6   0.727273
7   0.727273
8   1.727273
9   2.727273
10  2.727273
